local hit_test = require("framework.hit_test")
local list = require("lib.list")

TestCase("framework.hit_test.hit_circle", function()
  local units = list.List:new()
  units:push_back({ pos_x = 1, pos_y = 1, size = 1 })
  units:push_back({ pos_x = 2, pos_y = 2, size = 1 })
  units:push_back({ pos_x = 3, pos_y = 3, size = 1 })
  local tester = hit_test.HitTest:new(units)
  local r = tester:hit_circle(1.5, 1.5, 0.5)
  AssertEqual(r, {units[1], units[2]})
  r = tester:hit_circle(2, 2, 1.5, 1.1)
  AssertEqual(r, {units[1], units[3]})
  tester:release()
end)
